BRACERY = ../../node_modules/bracery
ASSETS = ../../assets/js/wikimess

postinstall:
	cp $(BRACERY)/parsetree.js $(ASSETS)/parsetree.js
	cp $(BRACERY)/grammar/rhs.browser.js $(ASSETS)/rhs.js
	cp $(BRACERY)/grammar/rhs.js .
